### ISSUE TITLE
Transfer to libretro org

### ISSUE THREAD

**Issue by twinaphex** [r-type/mame2016-libretro#1]
Hi,

sorry for having not responded earlier so far.

I guess we can take on yet another core if you feel like we will run into difficulties updating MAME due to the non-libco code changes and so on.

You can transfer the repo to me and I'll transfer it to libretro organization again.

**Comment by r-type** [comment]
yes no problem i will do it ,before i just want check before android build with ndk13 and fix if not building fine before transferring

**Comment by r-type** [comment]
I'm waiting the build finish with ndk-13b.
If fine,  I'll push the fix and I'll transfer the core.

**Comment by r-type** [comment]
@twinaphex hex that fine now , I ll transfer it , don't forget to add it to my libretro repositories for admin right :)
